### ISSUE TITLE
Standard-Bilder für den Blog

### ISSUE THREAD

**Issue by joliyea** [okfde/codefor.de#10]
- Standard-Bilder für verschiedene Kategorien von Blogbeiträgen anlegen (& dokumentieren!!) -> "Ich habe gerade kein Foto / es ist zu groß / zu unscharf etc." darf kein Grund sein, um keinen Blogbeitrag zu veröffentlichen!

**Comment by iamsilvio** [comment]
Alternativ links zu 
https://github.com/heyalexej/awesome-images , 
ein repo mit einer Linksammlung bei der man Fotoquellen unter CC0 und ähnlichen freien Lizenzen findet
im Tutorial hinterlegen.

**Comment by sonjafischbauer** [comment]
we've fixed this issue on layer 7 - people now have a couple of sources for free and public domain images.
