### ISSUE TITLE
Interne Links prüfen und rewrites anlegen

### ISSUE THREAD

**Issue by Claudia309** [okfde/codefor.de#129]
Interne Links checken:

- Verweisen alle internen Links auf codefor.de? (Keine Links mehr mit dev.)

- Verweisen alle Links der alten Seite auf ihre Entsprechung bei der neuen? --> Rewrites anlegen z. B. 
https://codefor.de/assets/presse/20200409-CFG-Handbuch-Krisenresilienz.pdf auf https://codefor.de/documents/Handbuch-Krisenresilienz.pdf

**Comment by Claudia309** [comment]
Externe Links checken:

- Führen sie noch auf aktive Seiten?

- Wenn Nein, Link entfernen. Wenn es sehr viele sind: Ist es möglich, sie automatisiert mit so etwas wie "Link nicht mehr verfügbar" zu ersetzen?

**Comment by ubergesundheit** [comment]
- [ ] Stadtgeschichten fehlen (@ubergesundheit kümmert sich)

**Comment by Claudia309** [comment]
Stadtgeschichten sollen auf der neuen Seite nicht mehr sein. Die Links von der alten Seite hier bitte einfach auf die entsprechenden Projekte bei der neuen Seite verweisen. Danke!

**Comment by joliyea** [comment]
- @ubergesundheit zieht die Summit-Seite um
- @ubergesundheit zieht auch Wahlsalons mit um
- Code of Conduct ist in #117 
- cutepetsdenver ist auch in #117 gelöst
- noch offen: Digital Refugee Labs

**Comment by joliyea** [comment]
To Do:
- alte Seite https://codefor.de/projekte/alle/ wird zu neuer Seite https://dev.codefor.de/projekte/archiv/ (vmtl von Hand)

**Comment by ubergesundheit** [comment]
#135 fügte Summit, Wahlsalons & Digitalrefugeelabs hinzu

**Comment by ubergesundheit** [comment]
Fehlt noch:

- [ ] Adventskalender https://codefor.de/advent/ (kann ins archiv unter einem namen mit jahreszahl)
- [ ] Launch Page https://codefor.de/launch/ (kann ins archiv)
- [ ] opendataday https://codefor.de/opendataday/ (kann ins archiv mit einer jahreszahl)
- [ ] Dokumente aus https://github.com/okfde/dev.codefor.de/issues/129#issue-637068282

**Comment by ubergesundheit** [comment]
Auf der aktuellen codefor.de Seite gibt es einen rss feed der Blogposts. Das wäre zu schade diesen zu verlieren: https://codefor.de/feed.xml

**Comment by robbi5** [comment]
Auf https://codefor.de/ressourcen/ liegen noch Slidedecks und Flyer, die noch nicht umgezogen sind.

**Comment by ubergesundheit** [comment]
https://codefor.de/labs/ existiert, ist aber IMO auf unserer Seite nicht mehr verlinkt.

**Comment by joliyea** [comment]
Erledigt.
