### ISSUE TITLE
"Über uns"

### ISSUE THREAD

**Issue by joliyea** [okfde/codefor.de#13]
- kompakter, mehr auf den Punkt, aktueller, mehr Grafiken
- z.B. Blocksatz f. Text

**Comment by joliyea** [comment]
Aku

**Comment by digital-codes** [comment]
ich bastel mal dran ...

**Comment by wagnerpeer** [comment]
Auf der "Uber uns" Seite hat sich einiges getan. Ist dieser Issue noch aktuell?
