### ISSUE TITLE
Stadtgeschichten zu alter Blüte verhelfen

### ISSUE THREAD

**Issue by ubergesundheit** [okfde/codefor.de#133]
Und zwar sehen die Stadtgeschichten auf der aktuellen Seite echt gut aus, wäre schade wenn das verloren gehen würde.

- Stadtgeschichten -> Alle Informationen aus der Frontmatter wieder nutzbar machen
- blockquotes stylen

**Comment by iamsilvio** [comment]
@ubergesundheit fehlt hier noch was? Wenn ja was?

**Comment by ubergesundheit** [comment]
ne passt so denke ich.. https://codefor.de/blog/stadtgeschichten/
