### ISSUE TITLE
Es sollte möglich sein alle Blogposts auf einer Seite anzuzeigen.

### ISSUE THREAD

**Issue by ubergesundheit** [okfde/codefor.de#146]
Aktuell gibt es nur einen Button "WEITERE ANZEIGEN", der auch mit Javascript funktioniert.

Mein Vorschlag wäre es:

Mindestens:
- Eine Seite hinzuzufügen auf der alle Blogposts verlinkt sind

Besser:
- Eine Seite hinzuzufügen auf der alle Blogposts verlinkt sind
- Die aktuelle Lösung durch eine klassische Pagination zu ersetzen, die würde dann auch ohne Javascript funktionieren.

**Comment by iamsilvio** [comment]
Das Paging auf der aktuellen Blog Übersicht basiert nicht mehr auf js
