### ISSUE TITLE
Tweets by codeforde verstecken wenn das Widget nicht geladen werden kann

### ISSUE THREAD

**Issue by ubergesundheit** [okfde/codefor.de#147]
Ich hab irgendwas geblockt, so siehts bei mir aus:

![image](https://user-images.githubusercontent.com/1494211/84743191-e25c6680-afb1-11ea-85ca-c4c63a7fecad.png)

Vorschlag: Das Widget wird durch einen Link zu https://twitter.com/codeforde ersetzt wenn da was nicht geladen werden kann.

**Comment by ubergesundheit** [comment]
Firefox mit uBlock Origin, Privacy Possum und der in Firefox eingebauten Strikten Tracking Protection

![image](https://user-images.githubusercontent.com/1494211/94897939-ee9cfe80-0490-11eb-9318-3620f1bca92d.png)

**Comment by digital-codes** [comment]
Ja, das ist ein Link, sieht aber nicht gut aus.
Ich könnte die Kachel ausblenden, wenn der Feed nicht geladen wird (bzw umgekehrt). Unser Twitter Logo steht sowieso unten dran. Oder wir rufen Twitter per API ab und schreiben die letzten Tweets selbst in das Fenster?

**Comment by ubergesundheit** [comment]
> Ich könnte die Kachel ausblenden, wenn der Feed nicht geladen wird (bzw umgekehrt).

gerne

**Comment by ubergesundheit** [comment]
Gelöst durch https://github.com/okfde/codefor.de/pull/217
