### ISSUE TITLE
Invalid usage of style tag

### ISSUE THREAD

**Issue by rowbean** [okfde/codefor.de#169]
The `<style>` element must be included inside the `<head>` of the document to be valid.
Found in https://github.com/okfde/dev.codefor.de/blob/dev/themes/codefor-theme/layouts/shortcodes/home/teaser-climate.html

**Comment by wagnerpeer** [comment]
What about writing the style within the corresponding tag?

**Comment by michael-k** [comment]
Inline styles should work since there's no `Content-Security-Policy` header.

**Comment by ubergesundheit** [comment]
I would vouch against using inline styles.

Better add these styles through an own file [here](https://github.com/okfde/codefor.de/tree/main/themes/codefor-theme/assets/scss) and add then `@import` it in the [`main.scss`](https://github.com/okfde/codefor.de/blob/main/themes/codefor-theme/assets/scss/main.scss#L72).

**Comment by iamsilvio** [comment]
Issue on a stale Branch
