### ISSUE TITLE
Usage of whitespace in ID of footer element

### ISSUE THREAD

**Issue by rowbean** [okfde/codefor.de#170]
An ID must not contain any space characters(https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute)

Found in https://github.com/okfde/dev.codefor.de/blob/dev/themes/codefor-theme/layouts/partials/footer.html

**Comment by wagnerpeer** [comment]
For future work, the location of footer: themes/codefor-theme/layouts/partials/footer.html

Looks like the `id` and the `class` attribute got mixed.
