### ISSUE TITLE
Projekte nach Thema clustern

### ISSUE THREAD

**Issue by michaeljokf** [okfde/codefor.de#20]
Damit die Projektseite nicht wieder so überladen ist. Würde ich gerne eine Top 10 (maximal 10) Vorzeigeprojekte, die immer angezeigt werden. 
Darunter gibt es dann Themenbereiche: Umwelt, Mobilität, Politik, Gesellschaft

Jeder Projekteintrag muss also einem Themenbereich zugeordnet werden. So können diese dann auch auf den Themenseiten angezeigt werden. 

Falls jmd. das umsetzen kann, ich wüsste gerne mal wie die Projektseite aussähe, wenn da nur ca 10 Projekte stehen. 
Darunter dann nochmal per Themenbereich sortierbar! (Das können wir auch nachträglich hinzufügen). 

Eine zugegeben sehr subjektive Top 10 könnte sein: 
- Open Legal Data (Politik)
- Wo ist Markt (Gesellschaft)
- Klimawatch (Umwelt)
- Luftdaten.info (Umwelt)
- Trinkwasser (Umwelt)
- Zug-Direktverbindungen (Mobilität)
- Unfalldaten Münster (Mobilität)
- Politik-Bei-Uns (Politik)
- kleine Anfragen (Politik)

Hier geht es mir nur um aktuelle Projekte, die halbwegs gut kommunizierbar sind. Habe da natürlich nicht alles auf dem Schirm. Wir kuratieren das vor dem Launch in der Community ggf. über den Community Rat.

**Comment by joliyea** [comment]
ubergesundheit

**Comment by ubergesundheit** [comment]
#29 fügt eine willkürliche auswahl an projekten zu einer separaten liste "Showcase" hinzu.

**Comment by joliyea** [comment]
Erledigt.
