### ISSUE TITLE
Replace Mapbox Tiles by a different Tile Layer Provider (e.g. Carto)

### ISSUE THREAD

**Issue by joergreichert** [okfde/codefor.de#203]
As we have currently issues with the Mapbox tiles, I would suggest the following: 

https://leaflet-extras.github.io/leaflet-providers/preview/ shows some alternative background layer provider (not all listed are still working resp. free accessible)

Personally I prefer the CartoDB_Voyager style (code is shown when selecting on https://leaflet-extras.github.io/leaflet-providers/preview/):

```
var CartoDB_Voyager = L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
	subdomains: 'abcd',
	maxZoom: 19
});
```

**Comment by ubergesundheit** [comment]
Nice, do you want to pick this up?

**Comment by joergreichert** [comment]
Sure, will do so in the evening, maybe selecting a style that fits to color style of our hole site.

**Comment by ubergesundheit** [comment]
Resoled in #212
