### ISSUE TITLE
Allgemeine Struktur der Webseite

### ISSUE THREAD

**Issue by michaeljokf** [okfde/codefor.de#21]
Hallo zusammen :-) 
Hier nochmal die Gedanken, die ich mal mit unserer UX Designerin zusammengetragen habe. Ich würde die allgemeine Struktur gerne erstmal so umsetzen - und freue mich über Unterstützung! 

**Seite Über Uns**
- gibt Infos über das allgemeine Projekt 
- hier werden alle erstmal abgeholt 
- alle die mitmachen möchten - werden auf "Mitmachen" weitergeleitet 

**Seite Projekte** 
- hier wird eine Top10 der Projekte aufgelistet 
- außerdem eine Sortierung nach Themenbereich 
- jedes Projekt muss zu einem Themenbereich sortiert werden 

**Seite Themen**
- hab versucht Seite "Unterstützen" in Themen umzubennen siehe config file
- hier werden unsere Themenbereiche vorgestellt 
- mir schweben aktuell vier vor (mehr möglich)
- Umwelt, Mobilität, Politik, Gesellschaft 
- Auswahl eines der Themen --> Weiterleitung auf eine Unterseite (Umwelt, Mobilität, Politik, Gesellschaft) 
- auf den Unterseiten jeweils kurze Texte (ca. 2-3 Absätze) 
- darunter werden Projekte geteased 
- Die ganzen Unterseiten (als Entwickler, aus Politik) - brauchen wir nicht so ausführlich 

**Seite Die Labs**
- könnte m.E. in "Mitmachen" umbenannt werden 
- Einleitungstext zu CFG und wie man mitmacht (über Github / Slack) oder über Teilnahme an den Labs 
- Kalendar mit Labtreffen + Veranstaltungen 
- Karte für die Labs (Auswahl der Labunterseiten) 

**Seite Blog**
- bitte den blauen Button entfernen, habe es über config probiert - aber das hat nicht funktioniert.

**Comment by Claudia309** [comment]
Hi zusammen! 

Wir haben uns ein paar Änderungen übelegt, die die Struktur grundsätzlich nicht angreifen, aber die Themen anders zuordnen und die Seite entschlacken. Unser Vorschlag:

- Bei "Über uns" sprechen wir zusätzlich das Netzwerk mit an, also kurze Texte dazu, warum das, wofür wir stehen, auch für Verwaltungen, Politik etc. interessant ist. Dadurch wird "Mitmachen" auf die Zielgruppe der Lab-Aktiven ausgerichtet.

- "Unsere Themen" in "Unsere Ziele" unbenennen. Darunter sollen dann die Texte fallen, die auf der Startseite schon verlinkt sind, also Offene Daten, Tech ohne Selbstzweck, Öffentliches Geld - öffentliches Gut, Digitales Ehrenamt, Ökologische Nachhaltigkeit. Zu jedem Punkt steht dann ein kleiner Teaser und die ausführliche Textversion lässt sich ausklappen.

- Für die Themen Umwelt, Mobilität, Politik und Gesellschaft soll es dafür keine Texte geben. Das sind ja relativ intuitive Stichworte nach denen die Projekte gefiltert werden können, um nicht immer alle Projekte durcheinander angezeigt zu bekommen.

**Comment by joliyea** [comment]
Mit neuem Design erledigt.
