### ISSUE TITLE
Remove links to calendar

### ISSUE THREAD

**Issue by k-nut** [okfde/codefor.de#215]
No lab apart from Cologne uses the hosted nextcloud calendar but it is shown very prominently on the lab pages and on the main page. This creates the impression that we don't meet anymore and we (the @okfde/codeforde-devs) just discussed that we would like to remove it.
@weberius would it be ok for you if we removed it entirely or should we add some code to keep showing it on the Cologne lab page?

**Comment by weberius** [comment]
@k-nut there is no problem; obviously there is no one else using it. So please remove it.
