### ISSUE TITLE
Link Problem

### ISSUE THREAD

**Issue by digital-codes** [okfde/codefor.de#221]
Die Seite https://www.bva.bund.de/SharedDocs/Kurzmeldungen/DE/Behoerden/Beratung/OpenData/Aktuelles/2020/200520_CfG_Resilienz.html
zeigt auf unser Resilienzhandbuch, aber über einen falschen Link:
https://codefor.de/assets/presse/CFG-Handbuch-Krisenresilienz-von-Verwaltungen.pdf
Wahrscheinlich geht es schneller, das bei uns zu korrigieren, als dort.
ABER: es gibt ein Dokument in https://github.com/okfde/codefor.de/blob/main/static/documents/Handbuch-Krisenresilienz.pdf
das via https://codefor.de/documents/Handbuch-Krisenresilienz.pdf  erreichbar ist. Dann gibt es 3 Dokumente zum selben Thema in https://github.com/okfde/codefor.de/tree/main/content/ressourcen, die aber alle nicht erreichbar sind, jedenfalls finde ich keinen externen Link. Wer weiß, welches die richtige Version ist?
Dann ist mir noch aufgefallen, dass es keinerlei Meldung gibt, wenn man einen nicht-exisiterenden Link eingibt. Das ist etwas komisch, finde ich.

**Comment by saerdnaer** [comment]
Hmm, gibt auch noch https://codefor.de/ressourcen/Code-for-Germany_Handbuch-Krisenresilienz.pdf
