### ISSUE TITLE
Problematic Javascript based collapsibles

### ISSUE THREAD

**Issue by ubergesundheit** [okfde/codefor.de#228]
#216 #224 already got rid of js based collapsibles on projects and labs pages

We don't want these js based collapsibles for accessiblity reasons. People blocking scripts have no method of accessing the information.

Suggestion: Get rid of them where possible.

Also: Investigate a `<details>` based solution for places where these collapsibles make sense.

**Comment by sonjafischbauer** [comment]
we (@k-nut and Nora and I) are going through old issues. dear @ubergesundheit do you still care about this?
