### ISSUE TITLE
Projekte: Tote externe Links

### ISSUE THREAD

**Issue by johnjohndoe** [okfde/codefor.de#252]
Bei Browsen unserer Projekte fiel mir auf, dass oft **Links** zu externen Webseiten **nicht** mehr funktionieren. Meiner Meinung nach macht das einen schlechten Eindruck auf Besucher_innen unserer Seite und entmutigt weitere Projekte anzuschauen.

Daher denke, sollten wir externe Links **automatisch, regelmäßig prüfen** lassen und auf Fehler zeitnah reagieren. Das kann bedeuten, dass wir die Links **korrigieren** oder komplett **entfernen** (z.B. weil ein Projekt aktuell nicht mehr deployed ist).

**Comment by iamsilvio** [comment]
Steht auf meiner To-do-Liste, hab schon mal einen scan gemacht und da kamen 200 Tote links raus!
Wollte mal schauen, ob man das als non blocking workflow in github bauen kann!

**Comment by sonjafischbauer** [comment]
I am adding this issue to our endeavors in 2023 to update the webseite. attaching matching label and adding issue to project.

**Comment by sonjafischbauer** [comment]
@k-nut this is the issues about the dead links

**Comment by sonjafischbauer** [comment]
I would include not only project pages, but also **lab sub-pages**. 

-     check if links are still working
-     check if email addresses are still working
-     remove broken links as well as non-functioning email addresses

**Comment by johnjohndoe** [comment]
I like to recommend reopening this issue because I noticed dead links in the blog recently. I suggest running **automated checks regularly** via GitHub Actions.
