### ISSUE TITLE
Event Feed für CodeFor und Lab Events

### ISSUE THREAD

**Issue by iamsilvio** [okfde/codefor.de#262]
Feature Umfang muss noch genauer spezifiziert werden.

Aktueller Umfang
- Seite mit globalen events
- Events auf den Lab Seiten
- Events können entweder explizit auf eine Seite oder auf Lab und globalen feed eingestellt werden
- iCal download

Fragen:
- Einbinden externer event Schnittstellen???

Ref:
- https://github.com/okfde/codefor.de/issues/53

**Comment by sonjafischbauer** [comment]
closing this issue for now. can be reopened in the future if a (team of) expert(s) wants to take it on.
