### ISSUE TITLE
Attribution für Blog Header

### ISSUE THREAD

**Issue by k-nut** [okfde/codefor.de#283]
Wir benutzen aktuell für die Out in the Open Serie immer Bilder von Unsplash. Diese dürfen wir einfach so benutzen, wir haben aber mal darüber gesprochen, dass wir es schön fänden, auch da einen Link zu dem Originalwerk zu setzen.

Das lässt sich relativ leicht umsetzen und ich habe mal zwei Versionen ausprobiert. Die Frage ist jetzt nur: Welche gefällt uns besser. Attribution im Bild oder unterm Bild? An der Stelle habe ich mich auch gefragt, ob wir grundsätzlich Untertitel für Bilder brauchen. Ich glaube eigentlich nicht. Das `title` Attribution können wir natürlich nach wie vor setzen damit das beim Hover und falls das Bild nicht geladen werden konnte angezeigt werden kann.

|Unten Drunter|Inline|
|---|---|
|![Unten Drunter](https://user-images.githubusercontent.com/1096357/128665225-1bc68134-f0e3-4135-a91f-81d3eb235325.png)|![Inline](https://user-images.githubusercontent.com/1096357/128665227-915b8224-842d-4047-bdce-653d4a9e8ca5.png)|

Was denkt ihr?

Work In Progress Code liegt auf dem [blog-header-attribution branch](https://github.com/okfde/codefor.de/tree/blog-header-attribution)

**Comment by joergreichert** [comment]
Würde die Attribution unter dem Bild bevorzugen. Beim aktuellen Bild geht es noch mit der weißen Schrift, bei bunteren Bildern bekommt man dann später vielleicht Schwierigkeiten mit Platzierung und Schriftfarbe. In der Beschriftung würde eventuell noch der Link/Hinweis auf die Lizenz gehören, z.B. "(...), Lizenz: CC0", wie https://www.tutonaut.de/so-gehts-kostenlose-bilder-fuer-den-kommerziellen-gebrauch/ auch beschreibt. Dann hätten wir auch eine generelle Vorgehensweise auch bei anderen Blog-Einträgen von uns, wo die verwendeten Fotos anders lizenziert sind.

**Comment by iamsilvio** [comment]
Duplicate or related to https://github.com/okfde/codefor.de/issues/260
