### ISSUE TITLE
annotation destroys the layout

### ISSUE THREAD

**Issue by iamsilvio** [okfde/codefor.de#291]
![image](https://user-images.githubusercontent.com/1840449/131474290-a7342a44-6399-4398-ba4a-d19e2b71ffb9.png)

**Comment by k-nut** [comment]
@iamsilvio which browser/resolution is this?

**Comment by iamsilvio** [comment]
everything wider than 1260
- Firefox
- Chromium based
- Safari

**Comment by k-nut** [comment]
I'll take a look at this this weekend. Thanks for spotting it! 👀
