### ISSUE TITLE
decide on a new sitemap

### ISSUE THREAD

**Issue by sonjafischbauer** [okfde/codefor.de#405]
**Home**
Startsteite (= Textvorschlag von Nora aufteilen: ein Teil hierauf Startseite, ein Teil auf Community). 
=> Layout wie Vorlage, plus unten dran noch für Ziele einen Blogbeitrag featuren, mit Teasertext. 

**main navigation** 

- Community (= Mitmachen & Über uns; hier können Testimonials rein)
**=> Layout wie Vorlage von Nora 

- Blog: Struktur Bleibt wie es ist (Kacheln von Blogartikeln). Content: In Klammern "Blog" statt "was bei uns passiert"  Das Icon mit dem Arm weg und erstetzen durch Sprechblase (nice to have: Rufzeichen statt Fragezeichen). Twittercode raus. 

- Projekte: Struktur neu: Überschrift, Kurzer Text. Verlinken zu anderen Repos. Keine Filter. Einige Projekte als Highlights. 

- SPENDEN (new! integrieres betterplace Formular, wie bei okfn.de/spenden) 

**footer navigation**
- Code of Conduct (war: Grundsätze). Struktur bleibt gleich. Text: updaten.
- Impressum (inkl. Datenschutz): Struktur bleibt. Text: Hier auch Datenschutzerklärung dazu. 
- Datenschutzerklärung (als Link im Footer-Menu zum Anker auf der Impressum-Seite)

**these pages can be cut in my opinion**
- Ressourcen 
- Presse
- Ziele (Content woanders unterbringen)
- Datenschutz (add to Impressum)

**Comment by sonjafischbauer** [comment]
von JF mit Nora am 24. April 2023

Startseite: 
- Text: kurze Vorstellung
-  Video: CfG in ein paar Minuten; oder kleine Präsentation mit Voice Over; spielt automatisch ab
- Text: unsere Ziele
- Text: nformationen für Kommunen und Dienstleister

- auf allen Seiten die nicht der Blog sind eine Blogvorschau

**Comment by sonjafischbauer** [comment]
@k-nut we decided to keep the "Presse" page, because it's our only archive for both articles about us and articles/ presentations by us. (needs an editorial update, and @noratitz is on it)

Could you please add https://codefor.de/presse/ to the new footer menu? 

new footer nagivation would then look like this: 

- Code of Conduct
- Presse 
- Impressum
- Datenschutzerklärung (anchor to impressum)

In next steps, we might want to rename it (to Presse & Ressourcen or Presse & Publikationen), but that would be figured out by the editorial team later in process.

**Comment by sonjafischbauer** [comment]
@k-nut we're almost done with this issue!

two things remaining, before the new sitemap is completed:

when the new start page is published, please 

1) archive the current /ziele and /ressourcen pages. 
Their content has been integrated into the new start page. 

2) redirect both urls to start page. (if that is even necessary, I suspect this happens automatically)

afterwards, this issue is ready to be closed.

**Comment by k-nut** [comment]
@sonjafischbauer I added those two changes to PR #433 so that you can directly check it out there.

**Comment by sonjafischbauer** [comment]
everything done - thanks! closing the issue
