### ISSUE TITLE
Twitter Feed Startseite

### ISSUE THREAD

**Issue by Claudia309** [okfde/codefor.de#41]
Michael und ich haben uns gerade die Webseite angeschaut und fänden es super, wenn jemand unseren Twitter Feed noch auf der Startseite einbinden würde. Mag jemand einen Vorschlag machen? 
https://twitter.com/codeforde

**Comment by joliyea** [comment]
Ich überarbeite gerade sowieso das Layout der Startseite, das in einer ersten Version hoffentlich heute oder morgen online gehen soll. Ich schau mal, ob ich das technisch und datenschutzsicher hinbekomme, sonst baue ich erstmal einen Platzhalter ein.

**Comment by ubergesundheit** [comment]
Ist das noch relevant? Wir haben noch Issue https://github.com/okfde/codefor.de/issues/147 welches sich auch mit dem Twitter feed beschäftigt. Also bitte wieder aufmachen oder mit in #147 diskutieren
