### ISSUE TITLE
Allow loading more projects from lab specific sources

### ISSUE THREAD

**Issue by k-nut** [okfde/codefor.de#439]
As part of #425 @digital-codes and I talked about adding the option of loading more projects from lab specific sources. 

The lab in Karlsruhe has their own project list and would prefer not to keep the data redundantly in this repo as well. We have discussed an implementation in which they offer a JSON endpoint and we add some javascript to the codefor.de/projekte site which will query the JSON on page load and add the projects. This will not complicate the build process but will still allow us to use federated project listings without much additional effort.

**Comment by digital-codes** [comment]
There is an initial proposal for a projectlist here:
https://ok-lab-karlsruhe.de/projects/projectlist.json
I can add more elements if neccessary, but maybe it's already OK ?

**Comment by digital-codes** [comment]
Plus year and category list?

**Comment by ubergesundheit** [comment]
Also make sure to send correct CORS headers

**Comment by digital-codes** [comment]
Any ideas on how to proceed here?

**Comment by k-nut** [comment]
I have drafted a first version that loads the projects here: https://github.com/okfde/codefor.de/pull/449. Let me know what you think. ([Deploy Preview](https://deploy-preview-449--hungry-heisenberg-4bd67f.netlify.app/projekte/alle/))

**Comment by k-nut** [comment]
We landed the change that allows loading from third parties in #449. Closing as completed.
