### ISSUE TITLE
Allow sorting projects by publish date

### ISSUE THREAD

**Issue by k-nut** [okfde/codefor.de#441]
Currently, all projects are sorted alphabetically. It might be more interesting to sort them by publish date descending so that visitors can check out the most recent projects first. We should offer some kind of UI that allow for setting the sort to a-z/z-a/date ascending/date descending.

**Comment by sonjafischbauer** [comment]
This issue is solved, with the above mentioned pull requests, right, @k-nut ? please feel free to close it, or do you think we should keep it open because could be further optimized?

**Comment by k-nut** [comment]
Nope, I'll consider this done ✅
