### ISSUE TITLE
Alte URLs redirecten

### ISSUE THREAD

**Issue by tordans** [okfde/codefor.de#45]
"Just in case", damit es nicht vergessen wird.

Ich fände es sehr wichtig, dass alle URLs von der alten Website weiterhin auf eine sinnvolle, neue Seite leite – nach Möglichkeit nirgendwo 404-Seiten.

In der Jekyll-Welt muss man dafür häufig leider auf einen Meta-Tag + JavaScript-Hack zurückgreifen. Aber auch das ist IMO besser, als nichts :-).

**Comment by wagnerpeer** [comment]
Ist dies ein Issue fuer die neue, oder fuer die alte Seite?
Kannst du ein Beispiel nennen?

**Comment by jochenklar** [comment]
Die Labs habe neue URLs: https://www.codefor.de/berlin -> https://dev.codefor.de/labs/berlin. Das Lab ist aber überall mit der alten Adresse verlinkt.

**Comment by ubergesundheit** [comment]
Habe das mal in #87 für Münster ausprobiert. Hugo erstellt einen redirect für `alias` Einträge in der frontmatter. So leitet nun https://deploy-preview-87--dev-codefor-de.netlify.app/muenster/ nach https://deploy-preview-87--dev-codefor-de.netlify.app/labs/muenster/ um.

**Comment by michael-k** [comment]
Netlify kann auch Redirects und macht das nicht über HTML, sondern über den HTTP Statuscode (default: 301).
https://docs.netlify.com/routing/redirects/

**Comment by ubergesundheit** [comment]
Am Ende wird die Seite wohl auf nem okfde Server laufen, denke ich. Da ließen sich auch Redirects einstellen. Das ist aber dann nicht in diesem repository.//

**Comment by joliyea** [comment]
Ist gefixt.
