### ISSUE TITLE
Layout/Text von Themen Buttons

### ISSUE THREAD

**Issue by wagnerpeer** [okfde/codefor.de#49]
Die Buttons, die auf unsere Themen fuehren haben auf unterschiedlichen Seiten unterschiedliche Layouts als auch Texte.

| Seite | Layout | Text |
| --- | --- | --- |
| Startseite | Hintergrund: blau, Schrift: weiss | Zum Themenfeld |
| Themen | Hintergrund: gruen, Schriftgroesse: anders | Zum Themenfeld \<Themenfeld\> |

Eine vereinheitlichung waere interessant.

Zusaetzlich ist die Frage, ob Buttonaehnliche Elemente in diese Vereinheitlichung einbezogen werden: Lab Links und Links auf den Lab Seiten.

**Comment by joliyea** [comment]
Mit neuem Design erledigt.
