### ISSUE TITLE
Lab-Detailseiten

### ISSUE THREAD

**Issue by joliyea** [okfde/codefor.de#5]
- Treffpunkt
- Termine
- Kontakt / Ansprechpartner / Lab-Leads
- Projekte
- Links zu Meetup/gettogether/Github/Twitter/...
- Nice to have: Mini-Blog-Funktion für kleine Ankündigungen in wenigen Sätzen / Tweet-Integration / Fediverse-Integration oder irgendwie sowas halt.
- Idealzustand: Kein Lab braucht mehr eine eigene Seite, sondern alles kann hier abgebildet werden.

**Comment by ubergesundheit** [comment]
#25 #23 #14

**Comment by joliyea** [comment]
Termine -> Aku

**Comment by wagnerpeer** [comment]
Es fehlen noch Infos zu den Labs:
* Heidelberg
* Schleswig-Flensburg
* Mecklenburg-Vorpommern
* Bremen?

**Comment by ubergesundheit** [comment]
Schleswig-Flensburg: 
![CodeForSL-FL](https://user-images.githubusercontent.com/1494211/84654131-eedbb300-af0e-11ea-934b-850e3fb98841.png)

Quelle: https://drive.google.com/file/d/1mU50RLPUjkio5KtGUCSnmCg2eoVTbMpn/view?usp=sharing

Heidelberg:
![Xih5Kfot_400x400](https://user-images.githubusercontent.com/1494211/84654178-02871980-af0f-11ea-90fc-49eecc7c234e.jpg)


Quelle: https://twitter.com/OKL_HD/photo

**Comment by Claudia309** [comment]
Mecklenburg-Vorpommern  können wir löschen. Das war eine Struktur zur überregionalen Vernetzung, aber kein Lab per se und ist auch schon länger nicht mehr aktiv.

**Comment by Claudia309** [comment]
Paderborn gab es bisher noch nie, das war ein fiktives Beispiel für die Fallbeispiele im letzten Strategiecall ;)

**Comment by Claudia309** [comment]
Zu Bremen habe ich auch keine Infos, dass es dort ein OK Lab gibt. ist auch in der Übergabe von Michael nicht drin.

**Comment by ubergesundheit** [comment]
> Paderborn gab es bisher noch nie, das war ein fiktives Beispiel für die Fallbeispiele im letzten Strategiecall ;)

das glaube ich nicht. Die waren früher mal aktiv und hatten auch Projekte.. https://github.com/codeforpb

**Comment by ubergesundheit** [comment]
> Zu Bremen habe ich auch keine Infos, dass es dort ein OK Lab gibt. ist auch in der Übergabe von Michael nicht drin.

Bremen gibts auf der alten Seite zwar nicht, aber @arduina hat diesen commit gemacht: https://github.com/okfde/codefor.de/commit/55242fce77a8310ae62d25b8fadae0d7bf6aac3c

Kannst du dich erinnern @arduina ?

**Comment by Claudia309** [comment]
Verrückt, dann muss das spätestens unter Michael schon offiziell geschlossen worden sein, sonst hätte ich es ja in meiner Liste. Aber auch bei uns intern in der Cloud gibt es keine Infos dazu, also muss da schon mal eine Datenlöschung vorgefallen sein. Also bitte nicht wieder mit aufnehmen. Finde die Personen auch nicht im Slack. Das ist ein untrügliches Zeichen

**Comment by wagnerpeer** [comment]
Bitte nicht verwechseln mit codeforpb, da der Twitteraccount auf unsere Kolleg:innen in Palm Beach führt 😉
