### ISSUE TITLE
Terminkalender: Open Source Lösung

### ISSUE THREAD

**Issue by Claudia309** [okfde/codefor.de#53]
Gibt es da etwas?

**Comment by saerdnaer** [comment]
Sicher... Am sinnvollsten wäre was was einmal iCal-Feeds zusammenaggregiert, bei dem man dann aber auch selbst Einträge hinzufügen kann. Letzteres kann z.B. https://osmcal.org – https://github.com/thomersch/openstreetmap-calendar
