### ISSUE TITLE
Readme & Anleitung schreiben

### ISSUE THREAD

**Issue by ubergesundheit** [okfde/codefor.de#7]
Dieses Repository sollte eine Readme enthalten. Inhalt dieser Readme sollte sein:

- Worum es überhaupt geht
- Anleitung wie man Inhalte hinzufügt oder ändert
- Ansprechpartner bei Problemen

**Comment by iamsilvio** [comment]
Ihr habt euch Doku gewünscht, kann das einer von euch mal anschauen und freigeben PR #254
